[workspace]
members = [
    "cli",
    "sid",
    "pg",
    "encode",
]

# These profiles come from sid-pg. Not touching them for now.
[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
