[package]
name = "oid-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oid"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oid2 = { path = "..", features = ["uuid"] }
uuid = "1.3.1"
